#!/usr/bin/env bash
set -e

cmd=$1
shift || true

shdir=$(cd "$(dirname "$0")" && pwd)

function date_log {
   date +"%Y-%m-%d %H:%M:%S"
}
function log {
    echo "$(date_log) $@"
}
function log_exec {
    echo "$(date_log) $@" >> "$shdir/exec.log"
}
function log_compile {
    echo "$(date_log) $@" >> "$shdir/compile.log"
}
function to_vscode_debug_cmd {
args=(${@:2})

# program could also be $1
cat <<EOF
{
    "name": "Launch test/compile-devel",
    "type": "go",
    "request": "launch",
    "mode": "exec",
    "program": "test/compile-devel",
    "cwd": "test",
    "args": [
EOF
for arg in "${args[@]}";do
    echo "        \"$arg\","
done
cat <<EOF
    ],
    "env": {
        "COMPILER_ALLOW_REWRITE":"true",
        "COMPILER_DEBUG_IR_REWRITE_FUNC":"$COMPILER_DEBUG_IR_REWRITE_FUNC",
        "GOROOT": "../..",
        "PATH": "../../bin:\${env:PATH}"
    }
}
EOF
}

log_exec "$@"

# NOTE arg0 is exec_tool
# echo "arg 0 is $0"

base_name=$(basename "$1")
if [[ $base_name = compile ]];then
    pkg=$(echo "$@"|grep -oE -- "-p .*?( |$)"|cut -c 4-|tr -d ' ') # take package
    log_compile compile $pkg

    if [[ $pkg = runtime ]];then
       log_compile "runtime output: $@"
       log_compile "runtime output: $3"
       trap 'log_compile "runtime end"; cp "$3" "$shdir"/runtime.a ' EXIT
    fi

    if [[ $pkg = main || $pkg = github.com/xhd2015/go/cmd/test/pkg ]];then
       # dlv exec --api-version=2 --listen=localhost:2345 --check-go-version=false --headless -- "$PWD/compile-devel" "${@:2}"
       if [[ $cmd = debug ]];then
         log_compile "to debug with dlv: dlv exec --api-version=2 --listen=localhost:2345 --check-go-version=false --headless -- \"$shdir/compile-devel\" ${@:2}"
         vscode_debug_cmd=$(to_vscode_debug_cmd "$shdir/compile-devel" "${@:2}")
         log_compile "$vscode_debug_cmd"
         cat > "$(cd $shdir/.. && pwd)/.vscode/launch.json" <<EOF
{
    "version": "0.2.0",
    "configurations": [
        $vscode_debug_cmd
    ]
}
EOF
           sleep 6000
           exit
       fi
       # use custom compiler to compile
       log_compile "replace with compile-devel: $shdir/compile-devel ${@:2}"
       COMPILER_ALLOW_REWRITE=true "$shdir/compile-devel" ${@:2}
       exit
    fi
    
fi
# $0       compile
# $1...    -V=full ... flags


# env is primarily for evaluate env pairs like A=B
env -- "$@"
